services:
  backend:
    build:
      context: ./backend

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: maintenance_db
      POSTGRES_USER: maintenance_user
      POSTGRES_PASSWORD: maintenance_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  postgres_data: